shared:
  box: bento/oracle-7.5
  non_rotational: 'on'

node1:
  vm_name: ol7_121_splex1
  mem_size: 4096
  cpus: 2
  public_ip: 192.168.56.101
  u01_disk: /temp/vdi/ol7_121_cplex1_u01.vdi

node5:
  vm_name: ol7_mssql1
  mem_size: 3072
  cpus: 1
  public_ip: 192.168.56.105
  u01_disk: /temp/vdi/ol7_mssql1_u01.vdi

