DROP DATABASE IF EXISTS [test]
GO

DROP USER IF EXISTS [splex];
GO

CREATE DATABASE [test]
ON
PRIMARY
( NAME = N'test', FILENAME = N'/var/opt/mssql/data/test.mdf', SIZE = 8MB, FILEGROWTH = 64MB )
LOG ON
( NAME = N'test_log', FILENAME = N'/var/opt/mssql/data/test_log.ldf', SIZE = 8MB, FILEGROWTH = 64MB )
COLLATE SQL_Latin1_General_CP1_CI_AS;
GO
USE [test];
GO

ALTER DATABASE [test] SET COMPATIBILITY_LEVEL = 140;
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
EXEC [sys].[sp_fulltext_database] @action = 'disable'
END;
GO
ALTER DATABASE [test] SET ANSI_NULL_DEFAULT OFF;
GO
ALTER DATABASE [test] SET ANSI_NULLS OFF;
GO
ALTER DATABASE [test] SET ANSI_WARNINGS OFF;
GO
ALTER DATABASE [test] SET AUTO_CREATE_STATISTICS ON;
GO
ALTER DATABASE [test] SET AUTO_UPDATE_STATISTICS ON;
GO
ALTER DATABASE [test] SET CURSOR_CLOSE_ON_COMMIT OFF;
GO
ALTER DATABASE [test] SET CONCAT_NULL_YIELDS_NULL OFF;
GO
ALTER DATABASE [test] SET QUOTED_IDENTIFIER OFF;
GO
ALTER DATABASE [test] SET RECURSIVE_TRIGGERS OFF;
GO
ALTER DATABASE [test] SET DISABLE_BROKER;
GO
ALTER DATABASE [test] SET PARAMETERIZATION SIMPLE;
GO
ALTER DATABASE [test] SET RECOVERY FULL;
GO
ALTER DATABASE [test] SET TARGET_RECOVERY_TIME = 60 SECONDS;
GO
ALTER DATABASE [test] SET PAGE_VERIFY CHECKSUM;
GO
EXEC sys.sp_changedbowner @loginame = N'sa', @map = false;
GO
USE master;
GO
