/*
Created: 04/09/2020
Modified: 04/09/2020
Model: Convert SQL Server
Database: MS SQL Server 2019
*/


-- Create tables section -------------------------------------------------

-- Table COUNTRIES
use test
go

CREATE TABLE [COUNTRIES]
(
 [COUNTRY_ID] Char(2) NOT NULL,
 [COUNTRY_NAME] Varchar(40) NULL,
 [REGION_ID] Decimal(38,0) NULL
)
go

-- Add keys for table COUNTRIES

ALTER TABLE [COUNTRIES] ADD CONSTRAINT [COUNTRY_C_ID_PK] PRIMARY KEY ([COUNTRY_ID])
go

-- Table DEPARTMENTS

CREATE TABLE [DEPARTMENTS]
(
 [DEPARTMENT_ID] Decimal(4,0) NOT NULL,
 [DEPARTMENT_NAME] Varchar(30) NOT NULL,
 [MANAGER_ID] Decimal(6,0) NULL,
 [LOCATION_ID] Decimal(4,0) NULL
)
go

-- Create indexes for table DEPARTMENTS

CREATE INDEX [DEPT_LOCATION_IX] ON [DEPARTMENTS] ([LOCATION_ID])
go

-- Add keys for table DEPARTMENTS

ALTER TABLE [DEPARTMENTS] ADD CONSTRAINT [DEPT_ID_PK] PRIMARY KEY ([DEPARTMENT_ID])
go

-- Table EMPLOYEES

CREATE TABLE [EMPLOYEES]
(
 [EMPLOYEE_ID] Decimal(6,0) NOT NULL,
 [FIRST_NAME] Varchar(20) NULL,
 [LAST_NAME] Varchar(25) NOT NULL,
 [EMAIL] Varchar(25) NOT NULL,
 [PHONE_NUMBER] Varchar(20) NULL,
 [HIRE_DATE] Datetime2 NOT NULL,
 [JOB_ID] Varchar(10) NOT NULL,
 [SALARY] Decimal(8,2) NULL,
 [COMMISSION_PCT] Decimal(2,2) NULL,
 [MANAGER_ID] Decimal(6,0) NULL,
 [DEPARTMENT_ID] Decimal(4,0) NULL
)
go

-- Create indexes for table EMPLOYEES

CREATE INDEX [EMP_DEPARTMENT_IX] ON [EMPLOYEES] ([DEPARTMENT_ID])
go

CREATE INDEX [EMP_JOB_IX] ON [EMPLOYEES] ([JOB_ID])
go

CREATE INDEX [EMP_MANAGER_IX] ON [EMPLOYEES] ([MANAGER_ID])
go

CREATE INDEX [EMP_NAME_IX] ON [EMPLOYEES] ([LAST_NAME],[FIRST_NAME])
go

-- Add keys for table EMPLOYEES

ALTER TABLE [EMPLOYEES] ADD CONSTRAINT [EMP_EMP_ID_PK] PRIMARY KEY ([EMPLOYEE_ID])
go

-- Table EMPLOYEES_COPY

CREATE TABLE [EMPLOYEES_COPY]
(
 [EMPLOYEE_ID] Decimal(6,0) NULL,
 [FIRST_NAME] Varchar(20) NULL,
 [LAST_NAME] Varchar(25) NOT NULL,
 [EMAIL] Varchar(25) NOT NULL,
 [PHONE_NUMBER] Varchar(20) NULL,
 [HIRE_DATE] Datetime2 NOT NULL,
 [JOB_ID] Varchar(10) NOT NULL,
 [SALARY] Decimal(8,2) NULL,
 [COMMISSION_PCT] Decimal(2,2) NULL,
 [MANAGER_ID] Decimal(6,0) NULL,
 [DEPARTMENT_ID] Decimal(4,0) NULL
)
go

-- Table JOBS

CREATE TABLE [JOBS]
(
 [JOB_ID] Varchar(10) NOT NULL,
 [JOB_TITLE] Varchar(35) NOT NULL,
 [MIN_SALARY] Decimal(6,0) NULL,
 [MAX_SALARY] Decimal(6,0) NULL
)
go

-- Add keys for table JOBS

ALTER TABLE [JOBS] ADD CONSTRAINT [JOB_ID_PK] PRIMARY KEY ([JOB_ID])
go

-- Table JOB_HISTORY

CREATE TABLE [JOB_HISTORY]
(
 [EMPLOYEE_ID] Decimal(6,0) NOT NULL,
 [START_DATE] Datetime2 NOT NULL,
 [END_DATE] Datetime2 NOT NULL,
 [JOB_ID] Varchar(10) NOT NULL,
 [DEPARTMENT_ID] Decimal(4,0) NULL
)
go

-- Create indexes for table JOB_HISTORY

CREATE INDEX [JHIST_DEPARTMENT_IX] ON [JOB_HISTORY] ([DEPARTMENT_ID])
go

CREATE INDEX [JHIST_EMPLOYEE_IX] ON [JOB_HISTORY] ([EMPLOYEE_ID])
go

CREATE INDEX [JHIST_JOB_IX] ON [JOB_HISTORY] ([JOB_ID])
go

-- Add keys for table JOB_HISTORY

ALTER TABLE [JOB_HISTORY] ADD CONSTRAINT [JHIST_EMP_ID_ST_DATE_PK] PRIMARY KEY ([EMPLOYEE_ID],[START_DATE])
go

-- Table LOCATIONS

CREATE TABLE [LOCATIONS]
(
 [LOCATION_ID] Decimal(4,0) NOT NULL,
 [STREET_ADDRESS] Varchar(40) NULL,
 [POSTAL_CODE] Varchar(12) NULL,
 [CITY] Varchar(30) NOT NULL,
 [STATE_PROVINCE] Varchar(25) NULL,
 [COUNTRY_ID] Char(2) NULL
)
go

-- Create indexes for table LOCATIONS

CREATE INDEX [LOC_CITY_IX] ON [LOCATIONS] ([CITY])
go

CREATE INDEX [LOC_COUNTRY_IX] ON [LOCATIONS] ([COUNTRY_ID])
go

CREATE INDEX [LOC_STATE_PROVINCE_IX] ON [LOCATIONS] ([STATE_PROVINCE])
go

-- Add keys for table LOCATIONS

ALTER TABLE [LOCATIONS] ADD CONSTRAINT [LOC_ID_PK] PRIMARY KEY ([LOCATION_ID])
go

-- Table QUEST_TEMP_EXPLAIN

CREATE TABLE [QUEST_TEMP_EXPLAIN]
(
 [STATEMENT_ID] Varchar(30) NULL,
 [TIMESTAMP] Datetime2 NULL,
 [REMARKS] Varchar(80) NULL,
 [OPERATION] Varchar(30) NULL,
 [OPTIONS] Varchar(30) NULL,
 [OBJECT_NODE] Varchar(128) NULL,
 [OBJECT_OWNER] Varchar(30) NULL,
 [OBJECT_NAME] Varchar(30) NULL,
 [OBJECT_INSTANCE] Int NULL,
 [OBJECT_TYPE] Varchar(30) NULL,
 [OPTIMIZER] Varchar(255) NULL,
 [SEARCH_COLUMNS] Int NULL,
 [ID] Int NULL,
 [PARENT_ID] Int NULL,
 [POSITION] Int NULL,
 [COST] Int NULL,
 [CARDINALITY] Int NULL,
 [BYTES] Int NULL,
 [OTHER_TAG] Varchar(255) NULL,
 [PARTITION_START] Varchar(255) NULL,
 [PARTITION_STOP] Varchar(255) NULL,
 [PARTITION_ID] Int NULL,
 [OTHER] Text NULL,
 [DISTRIBUTION] Varchar(30) NULL,
 [CPU_COST] Int NULL,
 [IO_COST] Int NULL,
 [TEMP_SPACE] Int NULL,
 [ACCESS_PREDICATES] Varchar(4000) NULL,
 [FILTER_PREDICATES] Varchar(4000) NULL
)
go

-- Table REGIONS

CREATE TABLE [REGIONS]
(
 [REGION_ID] Decimal(38,0) NOT NULL,
 [REGION_NAME] Varchar(25) NULL
)
go

-- Add keys for table REGIONS

ALTER TABLE [REGIONS] ADD CONSTRAINT [REG_ID_PK] PRIMARY KEY ([REGION_ID])
go

-- Table TEST

CREATE TABLE [TEST]
(
 [ID] Decimal(38,0) NOT NULL,
 [DESCRIPTION] Varchar(100) NULL
)
go

-- Add keys for table TEST

ALTER TABLE [TEST] ADD CONSTRAINT [PK_TEST] PRIMARY KEY ([ID])
go
